name: Remote Deployment to Jetson

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Jetson via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying latest changes to Jetson..."
            
            # Repoyu güncelle
            cd /path/to/your/project/
            git pull origin main
            
            # Servisleri durdur, yeni imajları çek ve tekrar başlat
            docker compose down
            docker compose pull
            docker compose up -d --remove-orphans
            
            echo "Deployment successful."
